(function(){
  if(window.__rrtaAccreditationHistoryLoaded)return;window.__rrtaAccreditationHistoryLoaded=true;
  const page=(location.pathname.split('/').pop()||'').toLowerCase();
  if(!['learner-portal.html','manager-member.html'].includes(page))return;
  const SUPA='https://qgbpotjqggeodxqcwkgj.supabase.co',KEY='sb_publishable_J1yPM1Hi7INCX2m7rp3PdA_JdQ46FRS';
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const fmt=d=>d?new Date(d+'T12:00:00').toLocaleDateString('en-GB'):'—';
  const style=document.createElement('style');style.textContent=`
    .rrta-archive-panel{background:#fff;border:1px solid #e2e6ea;border-radius:14px;box-shadow:0 10px 24px rgba(18,24,33,.05);padding:18px;margin-top:15px}.rrta-archive-head{display:flex;align-items:center;justify-content:space-between;gap:14px;flex-wrap:wrap}.rrta-archive-head h2{margin:5px 0 4px}.rrta-archive-head p{margin:0;color:#6f7a88;font-size:11px}.rrta-archive-toggle{border:1px solid #d8dde4;background:#fff;color:#20262d;border-radius:8px;padding:8px 10px;font-size:9px;font-weight:850;cursor:pointer}.rrta-archive-list{display:none;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px;margin-top:14px}.rrta-archive-panel.open .rrta-archive-list{display:grid}.rrta-archive-card{position:relative;border:1px solid #e1e5e9;border-radius:10px;background:#f7f8fa;padding:14px 54px 14px 14px;min-height:126px}.rrta-archive-card h3{margin:0 0 8px;font-size:14px}.rrta-archive-card p{margin:4px 0;color:#6f7a88;font-size:9px}.rrta-archive-pill{display:inline-flex;border-radius:999px;padding:5px 8px;background:#eef1f4;color:#5b6572;font-size:8px;font-weight:900;position:absolute;right:12px;top:12px}.rrta-archive-view{position:absolute;right:12px;bottom:12px;width:34px;height:34px;border:1px solid #d7dde4;background:#fff;color:#20262d;border-radius:9px;display:grid;place-items:center;cursor:pointer}.rrta-archive-view:hover{background:#20262d;color:#fff}.rrta-archive-view svg{width:17px;height:17px;fill:none;stroke:currentColor;stroke-width:1.8}.rrta-archive-empty{padding:18px;text-align:center;color:#6f7a88;font-size:10px;border:1px dashed #d8dde4;border-radius:9px;grid-column:1/-1}@media(max-width:700px){.rrta-archive-list{grid-template-columns:1fr}}
  `;document.head.appendChild(style);
  let db,rows=[];
  async function signed(path){if(!path)return null;if(/^https?:\/\//i.test(path))return path;const clean=String(path).replace(/^\/+/, '').replace(/^learner-documents\//,'');const {data,error}=await db.storage.from('learner-documents').createSignedUrl(clean,300);return error?null:data?.signedUrl||null}
  function host(){if(page==='manager-member.html')return document.getElementById('certificates')?.closest('.panel');return document.getElementById('accreditationBody')?.closest('.panel')}
  async function render(){const h=host();if(!h)return setTimeout(render,250);document.getElementById('rrtaArchivedCertificates')?.remove();if(!rows.length)return;const panel=document.createElement('section');panel.id='rrtaArchivedCertificates';panel.className='rrta-archive-panel';panel.innerHTML=`<div class="rrta-archive-head"><div><div style="font-size:10px;color:#b20f22;font-weight:900;text-transform:uppercase;letter-spacing:.11em">Certificate History</div><h2>Archived Certificates</h2><p>${rows.length} previous certificate${rows.length===1?'':'s'} retained for audit and record history.</p></div><button class="rrta-archive-toggle" type="button">Show Archived (${rows.length})</button></div><div class="rrta-archive-list">${rows.map(r=>`<article class="rrta-archive-card"><span class="rrta-archive-pill">Archived</span><h3>${esc(r.accreditation_name)}</h3><p>${esc(r.awarding_body||'Awarding body not recorded')}</p><p>Issued ${fmt(r.issue_date)} · Expired ${fmt(r.expiry_date)}</p><p>Certificate: ${esc(r.certificate_number||'—')}</p>${r.certificate_url?`<button class="rrta-archive-view" type="button" data-archive-path="${esc(r.certificate_url)}" title="View archived certificate" aria-label="View archived certificate"><svg viewBox="0 0 24 24"><path d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6-9.5-6-9.5-6Z"/><circle cx="12" cy="12" r="2.5"/></svg></button>`:''}</article>`).join('')}</div>`;h.insertAdjacentElement('afterend',panel);const toggle=panel.querySelector('.rrta-archive-toggle');toggle.onclick=()=>{panel.classList.toggle('open');toggle.textContent=panel.classList.contains('open')?`Hide Archived (${rows.length})`:`Show Archived (${rows.length})`};panel.querySelectorAll('[data-archive-path]').forEach(b=>b.onclick=async()=>{b.disabled=true;const url=await signed(b.dataset.archivePath);b.disabled=false;if(url)window.open(url,'_blank','noopener,noreferrer');else alert('The archived certificate file could not be opened.')})}
  async function boot(n=0){if(!window.supabase?.createClient){if(n<30)setTimeout(()=>boot(n+1),200);return}db=window.supabase.createClient(SUPA,KEY);const {data:u}=await db.auth.getUser();if(!u?.user)return;const target=page==='manager-member.html'?new URLSearchParams(location.search).get('id'):u.user.id;if(!target)return;const {data,error}=await db.rpc('get_archived_accreditations',{target_learner_id:target});if(error)return;rows=data||[];render();window.addEventListener('focus',async()=>{const q=await db.rpc('get_archived_accreditations',{target_learner_id:target});if(!q.error){rows=q.data||[];render()}})}
  boot();
})();