const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../person-profile.js'),'utf8');
const base={id:'p1',full_name:'Alex Example',forename:'Alex',surname:'Example',personal_email:'alex@example.test',profile_id:null,default_company_id:null};
async function app(options={}){
 const nodes={},writes=[];let person={...base,...options.person};
 const get=id=>nodes[id]||(nodes[id]={value:'',disabled:false,textContent:'',innerHTML:'',appendChild(){}});
 Object.defineProperty(get('app'),'innerHTML',{set(html){this.html=html;for(const m of html.matchAll(/<input id="([^"]+)"[^>]*value="([^"]*)"/g))get(m[1]).value=m[2];get('person-company').value=person.default_company_id||'';get('person-notes').value=person.notes||'';get('person-fields').disabled=options.canEdit===false||!!person.profile_id;},get(){return this.html||''}});
 const db={auth:{getUser:async()=>options.auth||{data:{user:{id:'staff'}}}},rpc:async()=>({data:options.canEdit!==false}),from(table){let patch;const q={select(){return q},eq(){return q},is(){return q},order(){return q},single(){return q},update(p){patch=p;return q},then(resolve,reject){if(patch){writes.push(patch);if(!options.saveError&&!options.zeroRows)person={...person,...patch};}return Promise.resolve({data:patch&&options.zeroRows?null:table==='people'?person:[{id:'rrt',company_name:'Rapid Response Telecoms Ltd',active:true}],error:patch&&options.saveError?{message:'Access denied'}:null}).then(resolve,reject)}};return q;},storage:{from:()=>({createSignedUrl:async()=>({data:{signedUrl:'https://example.test/photo.png'}})})}};
 const context={document:{getElementById:get,createElement:()=>({remove(){}})},location:{search:options.noId?'':'?id=p1',href:''},URLSearchParams,supabase:{createClient:()=>db}};context.window=context;vm.runInNewContext(source,context);await new Promise(r=>setImmediate(r));
 return{get,writes,context,save:()=>get('person-form').onsubmit({preventDefault(){}})};
}
test('record opens without company or login account and offers editing',async()=>{const a=await app();assert.match(a.get('app').innerHTML,/Alex Example/);assert.match(a.get('app').innerHTML,/Company not assigned/);assert.equal(a.get('person-fields').disabled,false)});
test('assigning company saves the same person without creating an account',async()=>{const a=await app();a.get('person-company').value='rrt';await a.save();assert.equal(a.writes.length,1);assert.equal(a.writes[0].default_company_id,'rrt');assert.equal(a.writes[0].email,'alex@example.test');assert.ok(!('profile_id'in a.writes[0]));assert.match(a.get('app').innerHTML,/Company:<\/strong> Rapid Response/);assert.match(a.get('save-status').textContent,/Changes saved/)});
test('company can be cleared',async()=>{const a=await app({person:{default_company_id:'rrt'}});a.get('person-company').value='';await a.save();assert.equal(a.writes[0].default_company_id,null)});
test('required fields prevent saving invalid details',async()=>{const a=await app();a.get('person-forename').value='';await a.save();assert.equal(a.writes.length,0);assert.match(a.get('save-status').textContent,/Enter forename/)});
test('failed saves preserve edits and do not report success',async()=>{const a=await app({saveError:true});a.get('person-company').value='rrt';await a.save();assert.match(a.get('save-status').textContent,/Access denied/);assert.equal(a.get('person-company').value,'rrt');assert.equal(a.get('person-fields').disabled,false)});
test('zero-row updates cannot report success',async()=>{const a=await app({zeroRows:true});await a.save();assert.match(a.get('save-status').textContent,/No record was updated/)});
test('read-only users cannot save',async()=>{const a=await app({canEdit:false});await a.save();assert.equal(a.writes.length,0)});
test('signed-out and missing-ID pages show visible explanations',async()=>{const a=await app({auth:{data:{user:null}}});assert.match(a.get('app').innerHTML,/Sign in to view/);const b=await app({noId:true});assert.match(b.get('app').textContent,/No person was selected/)});
test('profile page supplies navigation shell and cannot remain hidden while nav loads',()=>{const html=fs.readFileSync(path.join(__dirname,'../person-profile.html'),'utf8');assert.match(html,/<div class="shell"><aside class="side">/);assert.match(html,/html\.rrta-nav-pending body\.person-record-page\{visibility:visible!important\}/)});
